version: "3"
services:
  cpu:
    build:
      context: ./docker
      dockerfile: Dockerfile.cpu
    tty: true
    working_dir: /work
    volumes:
      - $PWD:/work
    ports:
      - 6006:6006 # tensorboard
#      - 8888:8888 # jupyter notebook
